### ISSUE TITLE
Containerize with Docker MVP

### ISSUE THREAD

**Issue by signebedi** [libreForms/libreForms-flask#198]
It might be worth adding support for a dockerized application.

Ref:
1. https://jonathanmeier.io/containerize-flask-app-docker-compose/
2. https://pyshark.com/containerize-a-flask-application-using-docker/

An MVP will have basic functionality but not necessarily need custom forms, or anything like that. It should still probably get celery to work.

**Comment by signebedi** [comment]
We'll need a somewhat complex setup (docker compose) for this to work. End users will need their own config_overrides.py and form_config.py files. In addition, we'll need to add gunicorn and celery (task, beat, flower) support.

**Comment by hyp-er** [comment]
I created separate repo for this specific issue (See https://github.com/hyp-er/libreForms-docker).

**Comment by signebedi** [comment]
I think that we probably need to add example files for those that we usually require users to create, like config_overrides.py. We can put these under `etc/`.

**Comment by signebedi** [comment]
Okay, we can now run a basic docker container by running `docker-compose --env-file libreforms-docker.env up -d --remove-orphans`. Future work will add a celery and celerybeat daemon.

**Comment by signebedi** [comment]
It's an authentication problem:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/libreForms/app/mongo.py", line 152, in collections
    collections = db.list_collection_names()
  File "/usr/local/lib/python3.8/site-packages/pymongo/database.py", line 959, in list_collection_names
    return [result["name"] for result in self.list_collections(session=session, **kwargs)]
  File "/usr/local/lib/python3.8/site-packages/pymongo/database.py", line 911, in list_collections
    return self.__client._retryable_read(_cmd, read_pref, session)
  File "/usr/local/lib/python3.8/site-packages/pymongo/_csot.py", line 105, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1442, in _retryable_read
    with self._socket_from_server(read_pref, server, session) as (sock_info, read_pref):
  File "/usr/local/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1282, in _socket_from_server
    with self._get_socket(server, session) as sock_info:
  File "/usr/local/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1217, in _get_socket
    with server.get_socket(handler=err_handler) as sock_info:
  File "/usr/local/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.8/site-packages/pymongo/pool.py", line 1407, in get_socket
    sock_info = self._get_socket(handler=handler)
  File "/usr/local/lib/python3.8/site-packages/pymongo/pool.py", line 1520, in _get_socket
    sock_info = self.connect(handler=handler)
  File "/usr/local/lib/python3.8/site-packages/pymongo/pool.py", line 1378, in connect
    sock_info.authenticate()
  File "/usr/local/lib/python3.8/site-packages/pymongo/pool.py", line 870, in authenticate
    auth.authenticate(creds, self)
  File "/usr/local/lib/python3.8/site-packages/pymongo/auth.py", line 549, in authenticate
    auth_func(credentials, sock_info)
  File "/usr/local/lib/python3.8/site-packages/pymongo/auth.py", line 475, in _authenticate_default
    return _authenticate_scram(credentials, sock_info, "SCRAM-SHA-1")
  File "/usr/local/lib/python3.8/site-packages/pymongo/auth.py", line 201, in _authenticate_scram
    res = sock_info.command(source, cmd)
  File "/usr/local/lib/python3.8/site-packages/pymongo/pool.py", line 767, in command
    return command(
  File "/usr/local/lib/python3.8/site-packages/pymongo/network.py", line 166, in command
    helpers._check_command_response(
  File "/usr/local/lib/python3.8/site-packages/pymongo/helpers.py", line 181, in _check_command_response
    raise OperationFailure(errmsg, code, response, max_wire_version)
pymongo.errors.OperationFailure: Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed'}
```

**Comment by signebedi** [comment]
Okay, I think we got mongodb (and email?) working. Still need to add celery. Sometimes, the config override file doesn't copy over, so we can just re-copy using the following commands, then reload.

```bash
docker cp etc/config_overrides.py.example `docker ps -aqf name=libreforms`:/libreForms/app/___config_overrides.py
docker-compose up -d --remove-orphans
```

**Comment by signebedi** [comment]
So we keep getting a errno 111 connection refused, but the form submissions keep going through. It might have something to do with the naming of the mongo service, see https://stackoverflow.com/a/34711892/13301284, though the problem persisted even after ostensibly fixing it. It could also be a result of celery not working ... though I thought it would just be falling back to executing synchronously...

**Comment by signebedi** [comment]
Okay, we've implemented celery and celerybeat. They need to be tested to ensure they work correctly.

**Comment by signebedi** [comment]
We should find a way to run services - especially in Flask and Celery - using a non-root user like `libreforms`.

**Comment by signebedi** [comment]
Add flower service.

Optionally, we should find a way to run a celery flower server. It should be a 30-second process, just running from the existing Dockerfile but running `celery -A celeryd.celery flower --port=5555 --loglevel=info`.

**Comment by signebedi** [comment]
Okay, we've created follow on tasks for Docker, and met the MVP requirements for this task. Closing it for now.
