### ISSUE TITLE
Errno 111 connection refused, but the form submits on Docker

### ISSUE THREAD

**Issue by signebedi** [libreForms/libreForms-flask#219]
So we keep getting a errno 111 connection refused, but the form submissions keep going through. It might have something to do with the naming of the mongo service, see https://stackoverflow.com/a/34711892/13301284, though the problem persisted even after ostensibly fixing it. It could also be a result of celery not working ... though I thought it would just be falling back to executing synchronously...

_Originally posted by @signebedi in https://github.com/libreForms/libreForms-flask/issues/198#issuecomment-1399781921_

**Comment by signebedi** [comment]
The most recent version of this causes a full on auth failure:

```
>>> from app.mongo import mongodb, MongoDB
>>> mongodb.collections()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/libreForms/app/mongo.py", line 152, in collections
    collections = db.list_collection_names()
  File "/usr/local/lib/python3.8/site-packages/pymongo/database.py", line 959, in list_collection_names
    return [result["name"] for result in self.list_collections(session=session, **kwargs)]
  File "/usr/local/lib/python3.8/site-packages/pymongo/database.py", line 911, in list_collections
    return self.__client._retryable_read(_cmd, read_pref, session)
  File "/usr/local/lib/python3.8/site-packages/pymongo/_csot.py", line 105, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1442, in _retryable_read
    with self._socket_from_server(read_pref, server, session) as (sock_info, read_pref):
  File "/usr/local/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1282, in _socket_from_server
    with self._get_socket(server, session) as sock_info:
  File "/usr/local/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1217, in _get_socket
    with server.get_socket(handler=err_handler) as sock_info:
  File "/usr/local/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.8/site-packages/pymongo/pool.py", line 1407, in get_socket
    sock_info = self._get_socket(handler=handler)
  File "/usr/local/lib/python3.8/site-packages/pymongo/pool.py", line 1520, in _get_socket
    sock_info = self.connect(handler=handler)
  File "/usr/local/lib/python3.8/site-packages/pymongo/pool.py", line 1378, in connect
    sock_info.authenticate()
  File "/usr/local/lib/python3.8/site-packages/pymongo/pool.py", line 870, in authenticate
    auth.authenticate(creds, self)
  File "/usr/local/lib/python3.8/site-packages/pymongo/auth.py", line 549, in authenticate
    auth_func(credentials, sock_info)
  File "/usr/local/lib/python3.8/site-packages/pymongo/auth.py", line 475, in _authenticate_default
    return _authenticate_scram(credentials, sock_info, "SCRAM-SHA-1")
  File "/usr/local/lib/python3.8/site-packages/pymongo/auth.py", line 201, in _authenticate_scram
    res = sock_info.command(source, cmd)
  File "/usr/local/lib/python3.8/site-packages/pymongo/pool.py", line 767, in command
    return command(
  File "/usr/local/lib/python3.8/site-packages/pymongo/network.py", line 166, in command
    helpers._check_command_response(
  File "/usr/local/lib/python3.8/site-packages/pymongo/helpers.py", line 181, in _check_command_response
    raise OperationFailure(errmsg, code, response, max_wire_version)
pymongo.errors.OperationFailure: Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'AuthenticationFailed'}
```

**Comment by signebedi** [comment]
This might actually be an issue with emails, and specifically async email calls.

Ref: 
- https://stackoverflow.com/questions/72010714/python-sending-email-connectionrefusederror-errno-111-connection-refused-p

**Comment by signebedi** [comment]
Potential duplicate of #136 .
