### ISSUE TITLE
Bug with submission history

### ISSUE THREAD

**Issue by signebedi** [libreForms/libreForms-flask#230]
Not able to track down the specific error, but there is a bug when trying to access submission history.

**Comment by janoskabedis** [comment]
Seems like it might be caused by an attempt to access / drop the `Metadata` field without that field being properly set.

```
Traceback (most recent call last):
  File "/opt/libreForms/venv/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/libreForms/venv/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/libreForms/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/libreForms/venv/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/opt/libreForms/venv/lib/python3.8/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/opt/libreForms/app/views/submissions.py", line 735, in render_document_history
    ip=dict(list(dict(record['Metadata']).values())[0])['signature_ip'] if 'signature_ip' in dict(list(dict(record['Metadata']).values())[0])else None,
  File "/opt/libreForms/venv/lib/python3.8/site-packages/pandas/core/frame.py", line 3805, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/opt/libreForms/venv/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    raise KeyError(key) from err
KeyError: 'Metadata'
```

**Comment by signebedi** [comment]
Seems like it might be caused by an attempt to access / drop the Metadata field without that field being properly set.

```
Traceback (most recent call last):
  File "/opt/libreForms/venv/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/libreForms/venv/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/libreForms/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/libreForms/venv/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/opt/libreForms/venv/lib/python3.8/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/opt/libreForms/app/views/submissions.py", line 735, in render_document_history
    ip=dict(list(dict(record['Metadata']).values())[0])['signature_ip'] if 'signature_ip' in dict(list(dict(record['Metadata']).values())[0])else None,
  File "/opt/libreForms/venv/lib/python3.8/site-packages/pandas/core/frame.py", line 3805, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/opt/libreForms/venv/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    raise KeyError(key) from err
KeyError: 'Metadata'
```

**Comment by signebedi** [comment]
Fixed by adding a check for the `Metadata` key in the submission's keys, defaulting to None it isn't found.
