### ISSUE TITLE
[bug] sqlite database locked error during concurrent use

### ISSUE THREAD

**Issue by janoskabedis** [libreForms/libreForms-flask#453]
```
2023-10-12 16:58:36,727 - ERROR - Exception on /auth/login [POST] - 95c1ac5a-6920-11ee-a3c2-0a4c12e3a9b4
Traceback (most recent call last):
  File "/opt/libreForms/venv/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/opt/libreForms/venv/lib64/python3.8/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/libreForms/venv/lib64/python3.8/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/libreForms/venv/lib64/python3.8/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/libreForms/venv/lib64/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/libreForms/venv/lib64/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/opt/libreForms/app/views/auth.py", line 588, in login
    db.session.commit()
  File "/opt/libreForms/venv/lib64/python3.8/site-packages/sqlalchemy/orm/scoping.py", line 552, in commit
    return self._proxied.commit()
  File "/opt/libreForms/venv/lib64/python3.8/site-packages/sqlalchemy/orm/session.py", line 1920, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/opt/libreForms/venv/lib64/python3.8/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/opt/libreForms/venv/lib64/python3.8/site-packages/sqlalchemy/orm/session.py", line 1236, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/opt/libreForms/venv/lib64/python3.8/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/opt/libreForms/venv/lib64/python3.8/site-packages/sqlalchemy/orm/session.py", line 1211, in _prepare_impl
    self.session.flush()
  File "/opt/libreForms/venv/lib64/python3.8/site-packages/sqlalchemy/orm/session.py", line 4163, in flush
    self._flush(objects)
  File "/opt/libreForms/venv/lib64/python3.8/site-packages/sqlalchemy/orm/session.py", line 4299, in _flush
    transaction.rollback(_capture_exception=True)
  File "/opt/libreForms/venv/lib64/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/opt/libreForms/venv/lib64/python3.8/site-packages/sqlalchemy/orm/session.py", line 4259, in _flush
    flush_context.execute()
  File "/opt/libreForms/venv/lib64/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/opt/libreForms/venv/lib64/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/opt/libreForms/venv/lib64/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 85, in save_obj
    _emit_update_statements(
  File "/opt/libreForms/venv/lib64/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 909, in _emit_update_statements
    c = connection.execute(
  File "/opt/libreForms/venv/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
    return meth(
  File "/opt/libreForms/venv/lib64/python3.8/site-packages/sqlalchemy/sql/elements.py", line 483, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/opt/libreForms/venv/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 1635, in _execute_clauseelement
    ret = self._execute_context(
  File "/opt/libreForms/venv/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
    return self._exec_single_context(
  File "/opt/libreForms/venv/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
    self._handle_dbapi_exception(
  File "/opt/libreForms/venv/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/opt/libreForms/venv/lib64/python3.8/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/opt/libreForms/venv/lib64/python3.8/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: UPDATE user SET last_login=? WHERE user.id = ?]
[parameters: ('2023-10-12 16:58:31.713258', 1)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
```

**Comment by signebedi** [comment]
Add broader postgres support
Sqlite is not a good production database. Let's get broader postgres support on the books.

**Comment by signebedi** [comment]
This issue is an sqlite problem, not an application problem. That said, we can add better error handling into the login protocol, which we will do so you don't get an internal server error.
